package Comp;

public class Data {
	
	public String[][] tableSLR =
			//       0         1       2     3     4   5   6           7    8   9  10      11      12    13    14  15   16  17    18    19     20      21      22    23     24        25      26    27   28    29   30   31  32    33        34   35        36         37        38         39   40  41
		{       {"etat/VT","package","id","class","{","}","INS_LISTI","if","(",")","else","while","for",";","tab","[","]","int","float","char","string",":=","print","OPPRel","OPPArit","et","ou","NBR","FLT","$","S","PRG","CONTENT","IF","BOUCLE","DEC_LIST","DEC","TYPE","INS_LIST","INS","T","FNCT"},
				{"0","s2","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","1","err","err","err","err","err","err","err","err","err","err"},
				{"1","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","acc","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"2","err","s3","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"3","err","err","s4","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"4","err","s5","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"5","err","err","err","s6","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"6","err","s21","err","err","err","s9","s16","err","err","err","s17","s18","err","s20","err","err","s23","s24","s25","s26","err","s22","err","err","err","err","err","err","err","err","err","7","11","12","8","14","19","10","15","err","13"},
				{"7","err","err","err","err","s27","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"8","err","s21","err","err","r3","s9","s16","err","err","err","s17","s18","err","s20","err","err","s23","s24","s25","s26","err","s22","err","err","err","err","err","err","err","err","err","28","11","12","8","14","19","10","15","err","13"},
				{"9","err","s21","err","err","err","s9","s16","err","err","err","s17","s18","err","s20","err","err","s23","s24","s25","s26","err","s22","err","err","err","err","err","err","err","err","err","29","11","12","8","14","19","10","15","err","13"},
				{"10","err","err","err","err","r5","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"11","err","s21","err","err","r7","s9","s16","err","err","err","s17","s18","err","s20","err","err","s23","s24","s25","s26","err","s22","err","err","err","err","err","err","err","err","err","30","11","12","8","14","19","10","15","err","13"},
				{"12","err","s21","err","err","r11","s9","s16","err","err","err","s17","s18","err","s20","err","err","s23","s24","s25","s26","err","s22","err","err","err","err","err","err","err","err","err","31","11","12","8","14","19","10","15","err","13"},
				{"13","err","s21","err","err","r15","s9","s16","err","err","err","s17","s18","err","s20","err","err","s23","s24","s25","s26","err","s22","err","err","err","err","err","err","err","err","err","32","11","12","8","14","19","10","15","err","13"},
				{"14","err","err","err","err","err","err","err","err","err","err","err","err","s33","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"15","err","err","err","err","err","err","err","err","err","err","err","err","s34","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"16","err","err","err","err","err","err","err","s35","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"17","err","err","err","err","err","err","err","s36","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"18","err","err","err","err","err","err","err","s37","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"19","err","s38","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"20","err","s39","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"21","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s40","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"22","err","err","err","err","err","err","err","s41","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"23","err","r20","err","err","err","err","err","err","err","err","err","err","err","err","err","r20","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"24","err","r21","err","err","err","err","err","err","err","err","err","err","err","err","err","r21","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"25","err","r22","err","err","err","err","err","err","err","err","err","err","err","err","err","r22","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"26","err","r23","err","err","err","err","err","err","err","err","err","err","err","err","err","r23","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"27","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","r1","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"28","err","err","err","err","r2","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"29","err","err","err","err","r4","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"30","err","err","err","err","r6","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"31","err","err","err","err","r10","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"32","err","err","err","err","r14","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"33","err","r17","err","err","r17","r17","r17","err","err","err","r17","r17","err","s20","err","err","s23","s24","s25","s26","err","r17","err","err","err","err","err","err","err","err","err","err","err","err","42","14","43","err","err","err","err"},
				{"34","err","s21","err","err","r25","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s22","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","44","15","err","err"},
				{"35","err","s46","err","err","err","err","err","s47","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s48","s49","err","err","err","err","err","err","err","err","err","err","err","45","err"},
				{"36","err","s46","err","err","err","err","err","s47","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s48","s49","err","err","err","err","err","err","err","err","err","err","err","50","err"},
				{"37","err","s51","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"38","err","err","err","err","err","err","err","s52","err","err","err","err","r18","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"39","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s53","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"40","err","s46","err","err","err","err","err","s47","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s48","s49","err","err","err","err","err","err","err","err","err","err","err","54","err"},
				{"41","err","s46","err","err","err","err","err","s47","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s48","s49","err","err","err","err","err","err","err","err","err","err","err","55","err"},
				{"42","err","r16","err","err","r16","r16","r16","err","err","err","r16","r16","err","r16","err","err","r16","r16","r16","r16","err","r16","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"43","err","s56","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"44","err","err","err","err","r24","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"45","err","err","err","err","err","err","err","err","s57","err","err","err","err","err","err","err","err","err","err","err","err","err","s58","s59","s60","s61","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"46","err","err","err","err","err","err","err","err","r28","err","err","err","r28","err","err","err","err","err","err","err","err","err","r28","r28","r28","r28","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"47","err","s46","err","err","err","err","err","s47","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s48","s49","err","err","err","err","err","err","err","err","err","err","err","62","err"},
				{"48","err","err","err","err","err","err","err","err","r34","err","err","err","r34","err","err","err","err","err","err","err","err","err","r34","r34","r34","r34","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"49","err","err","err","err","err","err","err","err","r35","err","err","err","r35","err","err","err","err","err","err","err","err","err","r35","r35","r35","r35","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"50","err","err","err","err","err","err","err","err","s63","err","err","err","err","err","err","err","err","err","err","err","err","err","s58","s59","s60","s61","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"51","err","err","err","err","err","err","err","err","err","err","err","err","s64","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"52","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s23","s24","s25","s26","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","65","err","err","err","err"},
				{"53","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s23","s24","s25","s26","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","66","err","err","err","err"},
				{"54","err","err","err","err","err","err","err","err","r26","err","err","err","r26","err","err","err","err","err","err","err","err","err","s58","s59","s60","s61","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"55","err","err","err","err","err","err","err","err","s67","err","err","err","err","err","err","err","err","err","err","err","err","err","s58","s59","s60","s61","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"56","err","err","err","err","err","err","err","err","err","err","err","err","r18","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"57","err","err","err","s68","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"58","err","s46","err","err","err","err","err","s47","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s48","s49","err","err","err","err","err","err","err","err","err","err","err","69","err"},
				{"59","err","s46","err","err","err","err","err","s47","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s48","s49","err","err","err","err","err","err","err","err","err","err","err","70","err"},
				{"60","err","s46","err","err","err","err","err","s47","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s48","s49","err","err","err","err","err","err","err","err","err","err","err","71","err"},
				{"61","err","s46","err","err","err","err","err","s47","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s48","s49","err","err","err","err","err","err","err","err","err","err","err","72","err"},
				{"62","err","err","err","err","err","err","err","err","s73","err","err","err","err","err","err","err","err","err","err","err","err","err","s58","s59","s60","s61","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"63","err","err","err","s74","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"64","err","s46","err","err","err","err","err","s47","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s48","s49","err","err","err","err","err","err","err","err","err","err","err","75","err"},
				{"65","err","s76","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"66","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s77","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"67","err","err","err","err","err","err","err","err","r27","err","err","err","r27","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"68","err","s21","err","err","err","s9","s16","err","err","err","s17","s18","err","s20","err","err","s23","s24","s25","s26","err","s22","err","err","err","err","err","err","err","err","err","78","11","12","8","14","19","10","15","err","13"},
				{"69","err","err","err","err","err","err","err","err","r30","err","err","err","r30","err","err","err","err","err","err","err","err","err","s58","s59","s60","s61","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"70","err","err","err","err","err","err","err","err","r31","err","err","err","r31","err","err","err","err","err","err","err","err","err","s58","s59","s60","s61","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"71","err","err","err","err","err","err","err","err","r32","err","err","err","r32","err","err","err","err","err","err","err","err","err","s58","s59","s60","s61","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"72","err","err","err","err","err","err","err","err","r33","err","err","err","r33","err","err","err","err","err","err","err","err","err","s58","s59","s60","s61","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"73","err","err","err","err","err","err","err","err","r29","err","err","err","r29","err","err","err","err","err","err","err","err","err","r29","r29","r29","r29","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"74","err","s21","err","err","err","s9","s16","err","err","err","s17","s18","err","s20","err","err","s23","s24","s25","s26","err","s22","err","err","err","err","err","err","err","err","err","79","11","12","8","14","19","10","15","err","13"},
				{"75","err","err","err","err","err","err","err","err","err","err","err","err","s80","err","err","err","err","err","err","err","err","err","s58","s59","s60","s61","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"76","err","err","err","err","err","err","err","err","s81","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"77","err","err","err","err","err","err","err","err","err","err","err","err","r19","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"78","err","err","err","err","s82","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"79","err","err","err","err","s83","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"80","err","s21","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","s22","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","84","err","err"},
				{"81","err","err","err","s85","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"82","err","r9","err","err","r9","r9","r9","err","err","s86","r9","r9","err","r9","err","err","r9","r9","r9","r9","err","r9","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"83","err","r12","err","err","r12","r12","r12","err","err","err","r12","r12","err","r12","err","err","r12","r12","r12","r12","err","r12","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"84","err","err","err","err","err","err","err","err","s87","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"85","err","s21","err","err","err","s9","s16","err","err","err","s17","s18","err","s20","err","err","s23","s24","s25","s26","err","s22","err","err","err","err","err","err","err","err","err","88","11","12","8","14","19","10","15","err","13"},
				{"86","err","err","err","s89","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"87","err","err","err","s90","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"88","err","err","err","err","s91","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"89","err","s21","err","err","err","s9","s16","err","err","err","s17","s18","err","s20","err","err","s23","s24","s25","s26","err","s22","err","err","err","err","err","err","err","err","err","92","11","12","8","14","19","10","15","err","13"},
				{"90","err","s21","err","err","err","s9","s16","err","err","err","s17","s18","err","s20","err","err","s23","s24","s25","s26","err","s22","err","err","err","err","err","err","err","err","err","93","11","12","8","14","19","10","15","err","13"},
				{"91","err","r36","err","err","r36","r36","r36","err","err","err","r36","r36","err","r36","err","err","r36","r36","r36","r36","err","r36","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"92","err","err","err","err","s94","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"93","err","err","err","err","s95","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"94","err","r8","err","err","r8","r8","r8","err","err","err","r8","r8","err","r8","err","err","r8","r8","r8","r8","err","r8","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"},
				{"95","err","r13","err","err","r13","r13","r13","err","err","err","r13","r13","err","r13","err","err","r13","r13","r13","r13","err","r13","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err","err"}};





	
	
	public String[] LRGS = {
"S->PRG",
"PRG->package id class id { CONTENT }",
"CONTENT->DEC_LIST CONTENT",
"CONTENT->DEC_LIST",
"CONTENT->INS_LISTI CONTENT",
"CONTENT->INS_LIST",
"CONTENT->IF CONTENT",
"CONTENT->IF",
"IF->if ( T ) { CONTENT } else { CONTENT }",
"IF->if ( T ) { CONTENT }",
"CONTENT->BOUCLE CONTENT",
"CONTENT->BOUCLE",
"BOUCLE->while ( T ) { CONTENT }", 
"BOUCLE->for ( id ; T ; INS ) { CONTENT }",
"CONTENT->FNCT CONTENT",
"CONTENT->FNCT",
"DEC_LIST->DEC ; DEC_LIST",
"DEC_LIST->DEC ;",
"DEC->TYPE id",
"DEC->tab id [ TYPE ]", 
"TYPE->int",
"TYPE->float",
"TYPE->char",
"TYPE->string",
"INS_LIST->INS ; INS_LIST",
"INS_LIST->INS ;",
"INS->id := T", 
"INS->print ( T )",
"T->id", 
"T->( T )",
"T->T OPPRel T", 
"T->T OPPArit T", 
"T->T et T",
"T->T ou T",
"T->NBR", 
"T->FLT",
"FNCT->TYPE id ( TYPE id ) { CONTENT }"
};
	
	public static void main(String[] args) {
		Data d=new Data();
		for (int i=0;i<42;i++)
		System.out.println("tab[0]["+i+"]="+d.tableSLR[0][i]);
	}
}
